### ISSUE TITLE
Error with single underline function

### ISSUE THREAD

**Issue by ghost** [adrianbj/FieldtypePhone#1]
https://github.com/adrianbj/FieldtypePhone/blob/0460698ecdb89059e4fd7dee05ba5f4f096f82bd/InputfieldPhone.module#L186

Getting an error on this line, changed it to (not single but double underscore after "="):
`$f->description = __('Whether to ask for extension when entering phone numbers.', __FILE__);`

**Comment by adrianbj** [comment]
Thanks @godmok - accidentally introduced that yesterday. Fixed by https://github.com/adrianbj/FieldtypePhone/commit/525ef9a8a9359ba232dcdbe535da1f4fe8418de1
