### ISSUE TITLE
The field does not report changes

### ISSUE THREAD

**Issue by kunago** [adrianbj/FieldtypePhone#4]
I am using caching on my site and store also the phone field data into one variable. Then on a field change, the proper cache variable is emptied. The phone field does not report value changes to Processwire on save so for instance making use of this hook does not trigger the cache drop.

```
$this->addHookAfter('Pages::saved', function(HookEvent $event) {
  $page    = $event->arguments(0);
  $changes = $event->arguments(1);
  $values  = $event->arguments(2);

  if (!empty($changes)) {
    # if there is a change in data of a field, the according cache should be emptied
  }
}
```

**Comment by adrianbj** [comment]
Thanks @kunago - should be fixed in the latest version.
